name: www.jensaltheimer.com
favicon: null
layout_spectrum: 0.87861
typography_spectrum: 0.2931
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#220005'
    - '#ff5f7a'
    - '#2916b2'
    - '#cf0a39'
    - '#9b16a8'
  brandStrength: 0.125
  lightness: 0.625
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
