name: www.jensaltheimer.com
favicon: null
layout_spectrum: 0.93931
typography_spectrum: 0.2931
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6aba4c'
    - '#ffffff'
    - '#c7b589'
    - '#231f20'
    - '#fad73e'
  brandStrength: 0.0625
  lightness: 0.375
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
