name: www.jensaltheimer.com
favicon: null
layout_spectrum: 0.88536
typography_spectrum: 0.2931
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.0625
  lightness: 0.75
  saturation: 0.6875
  rhythmicContrast: 1
purpose: []
